spring:
  profiles:
    active: local
  liquibase:
    enabled: true
    change-log: classpath:migrations/1.0/changelog-1.0.xml
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: com.backend_tutorial.course_erp.models.mybatis